version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    container_name: answer_question_app
    restart: always
    image: valentaine98/my-test-app:latest
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env

volumes:
  postgres_data: